apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  DB_HOST: "mariadb"
  MYSQL_ROOT_PASSWORD: "test"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "test"
  MYSQL_DATABASE: "mariadb"